GET http://localhost:9000/api/flashcards
Accept: application/json

###

GET http://localhost:9000/api/flashcards/next
Accept: application/json

###

PATCH http://localhost:9000/api/flashcards/3/view
Accept: application/json

###
