GET http://localhost:9000/api/flashcards
Accept: application/json

###

GET http://localhost:9000/api/flashcards/next
Accept: application/json

###

POST http://localhost:9000/api/flashcards/15/review
Accept: application/json
Content-Type: application/json

{
  "level": 1
}

###

GET http://localhost:9000/api/flashcards/15
Accept: application/json

###
